version: '2'

services:
  desadb:
    image: mysql:5.6
    container_name: "desadb"
    hostname: desadb
    restart: always
    networks:
      opensid:
        ipv4_address: 172.27.17.2
    environment:
      - MYSQL_DATABASE=opensid_db
      - MYSQL_USER=opensid
      - MYSQL_PASSWORD=passwdPalingSusahDitebak
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  opensid:
    image: opensid:latest
    container_name: "opensid"
    hostname: opensid
    networks:
      opensid:
        ipv4_address: 172.27.17.1
    depends_on:
      - desadb
    environment:
      - SERVER_NAME=opensid.idjavahost.com
      - USERNAME=desaku
      - USERGROUP=desaku
      - SSH_PASSWORD=qwerty
      - ADMIN_USERNAME=superman
      - ADMIN_PASSWORD=987654321
      - DATABASE_HOSTNAME=172.27.17.2
      - DATABASE_USERNAME=opensid
      - DATABASE_PASSWORD=passwdPalingSusahDitebak
      - DATABASE_NAME=opensid_db
      - REAL_IP_FROM=172.27.17.0/24
    ports:
      - "2345:2345"
      
networks:
  opensid:
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.17.0/24
         gateway: 172.27.17.254
