version: '2'

services:
  desadb:
    image: mysql:5.6
    container_name: "desadb"
    hostname: desadb
    restart: always
    networks:
      opensid:
        ipv4_address: 10.10.0.2
    environment:
      - MYSQL_DATABASE=opensid_db
      - MYSQL_USER=opensid
      - MYSQL_PASSWORD=passwdPalingSusahDitebak
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /tmp/mysql:/var/lib/mysql

  opensid:
    image: idjavahost/opensid:latest
    container_name: "opensid"
    hostname: opensid
    networks:
      opensid:
        ipv4_address: 10.10.0.10
    depends_on:
      - desadb
    environment:
      - SERVER_NAME=opensid.idjavahost.com
      - USERNAME=desaku
      - USERGROUP=desaku
      - SSH_PASSWORD=qwerty
      - ADMIN_USERNAME=superman
      - ADMIN_PASSWORD=987654321
      - DATABASE_HOSTNAME=10.10.0.2
      - DATABASE_USERNAME=opensid
      - DATABASE_PASSWORD=passwdPalingSusahDitebak
      - DATABASE_NAME=opensid_db
    ports:
      - "2122:22"
      - "88:80"

networks:
  opensid:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/24
         gateway: 10.10.0.1
